#!/bin/bash
root@9e37d71d2e42:/alx-zero_day/0x03-git/bash#cat alx
root@9e37d71d2e42:/alx-zero_day/0x03-git/bash# cat > alx                                                                                        
#!/bin/bash
ALXroot@9e37d71d2e42:/alx-zero_day/0x03-git/bash# cat alx
#!/bin/bash
echo "ALX"
#!/bin/bash\necho "ALX"
echo "ALX School"
#!/bin/bash
